# Generated by Django 4.1.13 on 2024-05-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserEmail', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('UserPassword', models.CharField(max_length=100)),
                ('UserName', models.CharField(max_length=100)),
            ],
        ),
    ]
