# Generated by Django 5.0.4 on 2024-05-03 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_mymodel'),
        ('authtoken', '0004_alter_tokenproxy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authtoken.token'),
        ),
    ]
