# Generated by Django 5.0.4 on 2024-05-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mymodel_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
