# Generated by Django 4.1.13 on 2024-05-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marque', models.CharField(max_length=15)),
                ('Modèle', models.CharField(max_length=15)),
                ('Puissance_fiscale', models.IntegerField()),
                ('Transmission', models.CharField(max_length=15)),
                ('Kilométrage', models.IntegerField()),
                ('mise_en_circulation', models.FloatField()),
                ('cylindre', models.IntegerField()),
                ('Énergie', models.CharField(max_length=15)),
            ],
        ),
    ]
